# library(tidyverse)
# library(httr)
library(magrittr)

# 1. faça rodar tab_twitter <- rtweet::get_my_timeline()

tab_twitter <- rtweet::get_my_timeline()


# 2. Rode tibble::glimpse(dplyr::select(tab_twitter, 1:20), 80)
## e cole o resultado abaixo. Deixe o resultado como um comentário
## Dica: Selecione as linhas que deseja comentar e aplique Ctrl+Shift+C



# > tibble::glimpse(dplyr::select(tab_twitter, 1:20), 80)
# Rows: 100
# Columns: 20
# $ user_id              <chr> "376478408", "43186378", "380816062", "6135622...
# $ status_id            <chr> "1328322082116079616", "1328322052047171590", ...
# $ created_at           <dttm> 2020-11-16 13:00:38, 2020-11-16 13:00:30, 202...
# $ screen_name          <chr> "ocefpaf", "CMastication", "eLife", "dw_espano...
# $ text                 <chr> "Daqui à pouco no Natal do brasileiro :-( http...
# $ source               <chr> "Twitter for Android", "Twitter for iPad", "Bu...
# $ display_text_width   <dbl> 40, 176, 177, 277, 199, 133, 173, 134, 276, 22...
# $ reply_to_status_id   <chr> NA, "1328321152066973698", NA, NA, NA, NA, NA,...
# $ reply_to_user_id     <chr> NA, "21506708", NA, NA, NA, NA, NA, "766076461...
# $ reply_to_screen_name <chr> NA, "gvwilson", NA, NA, NA, NA, NA, "miglsoare...
# $ is_quote             <lgl> TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE,...
# $ is_retweet           <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALS...
# $ favorite_count       <int> 0, 0, 0, 0, 5, 0, 0, 0, 24, 1, 0, 0, 0, 0, 3, ...
# $ retweet_count        <int> 0, 0, 0, 3, 2, 0, 0, 0, 0, 0, 972, 142, 9664, ...
# $ quote_count          <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
# $ reply_count          <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
# $ hashtags             <list> [NA, NA, NA, <"Alemania", "DWNoticias">, "IBG...
# $ symbols              <list> [NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
# $ urls_url             <list> ["twitter.com/gvwilson/statu…", NA, "elifesci...
#                                $ urls_t.co            <list> ["https://t.co/lDJkzj9G7E", NA, "https://t.co...


# 3. [extra] faça uma tabela mostrando apenas as colunas "screen_name" e "text",
# agrupando pela coluna "screen_name" usando reactable::reactable().
## Dica: use o parâmetro groupBy= do reactable::reactable()

tab_twitter %>%
  dplyr::select(screen_name, text) %>%
  reactable::reactable(groupBy = "screen_name")

